"""
Loader for im2_tracker.csv — de-identified IM2 Patient Tracker.

Generated by deidentify_tracker.py from CCRx Onboarding.xlsx (IM2 sheet).
Patient names are initials only; Phone Number and DOB are stripped.

Columns: Date, Patient Name, Medication, Telehealth Date, Insurance Type,
         Provider, Pharmacy, Status, Tracking Number, PA Key, PA Dates,
         Insight Team Notes, COPAY CARD
"""

import pandas as pd
import streamlit as st

from config.settings import PATIENT_TRACKER_FILE


@st.cache_data(show_spinner=False)
def load_patient_tracker() -> pd.DataFrame:
    """Return patient tracker DataFrame, or empty DF if file missing."""
    try:
        df = pd.read_csv(PATIENT_TRACKER_FILE)
    except Exception:
        return pd.DataFrame()

    if df.empty or "Patient Name" not in df.columns:
        return pd.DataFrame()

    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    for col in ["Patient Name", "Status", "Provider", "Pharmacy"]:
        if col in df.columns:
            df[col] = df[col].fillna("").astype(str).str.strip()

    for col in ["Medication", "Insight Team Notes", "Insurance Type", "Tracking Number"]:
        if col in df.columns:
            df[col] = df[col].fillna("").astype(str).str.strip()

    return df[df["Patient Name"].str.strip() != ""].copy()


def filter_tracker_by_doctors(df: pd.DataFrame, doctor_list: list) -> pd.DataFrame:
    """Return rows whose Provider fuzzy-matches any name in doctor_list."""
    if df.empty or not doctor_list:
        return df.iloc[0:0]

    def _words(s: str) -> set:
        return {w.lower().strip(".,") for w in str(s).split() if len(w) > 2}

    targets = [_words(d) for d in doctor_list]

    def matches(provider: str) -> bool:
        if not provider:
            return False
        pwords = _words(provider)
        return any(pwords & t for t in targets)

    return df[df["Provider"].apply(matches)].copy()
